version: "3.8" # версия вашего docker-compose
services: # имеджи, которые запустятся по вашему желанию
  db: # название моего имеджа
    image: postgres:12 # скачает image postgres 12 версии
    volumes: # часть настроек для хранения данных, пока для нас это не важно
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
    ports: # порты
      - "5432:5432"
    environment: # переменные окружения, меняйте их если хотите поменять пароль, логин или название стартовой базы данных
      POSTGRES_USER: bmstu_user
      POSTGRES_DB: bmstu
      POSTGRES_PASSWORD: bmstu_password
    networks:
      - app_net

  adminer: # adminer db client
    image: adminer
    ports:
      - 8888:8080
    networks:
      - app_net
  minio:
    image: minio/minio
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: USER
      MINIO_ROOT_PASSWORD: 1234567890
    command: server --console-address ":9001" /data
networks:
  app_net:
    driver: bridge
volumes: # часть настроек для хранения данных
  postgresdb-data:
    driver: local
  minio-data:
