import image from "./assets/М11.png"

const testData = {
    requestID: 0,
    roads: [
        {
            Roadid: 1,
            Name: "М-1 'Беларусь' 33км-66км",
            Trustmanagment: 516,
            Length: 456,
            Paidlength: 33,
            Category: "1Б, 1В",
            Numberofstripes: "4-8",
            Speed: 110,
            Price: 150,
            Image: image,
            Statusroad: "active",
            Startofsection: 33,
            Endofsection: 66,
        },
        {
        Roadid: 2,
        Name: "М-3 'Украина' 24км-50км",
        Trustmanagment: 454,
        Length: 510,
        Paidlength: 70,
        Category: "1Б, II, III",
        Numberofstripes: "2-8",
        Speed: 110,
        Price: 260,
        Image: image,
        Statusroad: "active",
        Startofsection: 24,
        Endofsection: 50,
      },
      {
        Roadid: 3,
        Name: "М-3 'Украина' 50км-94км",
        Trustmanagment: 454,
        Length: 510,
        Paidlength: 70,
        Category: "1Б, II, III",
        Numberofstripes: "2-8",
        Speed: 110,
        Price: 260,
        Image: image,
        Statusroad: "active",
        Startofsection: 50,
        Endofsection: 94,
      },
      {
        Roadid: 4,
        Name: "М-4 'Дон' 21км-93км",
        Trustmanagment: 1930,
        Length: 1542,
        Paidlength: 1042,
        Category: "1А, 1Б, 1В, II",
        Numberofstripes: "2-8",
        Speed: 130,
        Price: 200,
        Image: image,
        Statusroad: "active",
        Startofsection: 21,
        Endofsection: 93,
      },
      {
        Roadid: 5,
        Name: "М-4 'Дон' 93км-211км",
        Trustmanagment: 1930,
        Length: 1542,
        Paidlength: 1042,
        Category: "1А, 1Б, 1В, II",
        Numberofstripes: "2-8",
        Speed: 130,
        Price: 200,
        Image: image,
        Statusroad: "active",
        Startofsection: 93,
        Endofsection: 211,
      },
      {
        Roadid: 6,
        Name: "М-4 'Дон' 211км-266км",
        Trustmanagment: 1930,
        Length: 1542,
        Paidlength: 1042,
        Category: "1А, 1Б, 1В, II",
        Numberofstripes: "2-8",
        Speed: 130,
        Price: 200,
        Image: image,
        Statusroad: "active",
        Startofsection: 211,
        Endofsection: 266,
      },
      {
        Roadid: 7,
        Name: "М-4 'Дон' 266км-322км",
        Trustmanagment: 1930,
        Length: 1542,
        Paidlength: 1042,
        Category: "1А, 1Б, 1В, II",
        Numberofstripes: "2-8",
        Speed: 130,
        Price: 200,
        Image: image,
        Statusroad: "active",
        Startofsection: 266,
        Endofsection: 322,
      },
      {
        Roadid: 8,
        Name: "М-4 'Дон' 322км-401км",
        Trustmanagment: 1930,
        Length: 1542,
        Paidlength: 1042,
        Category: "1А, 1Б, 1В, II",
        Numberofstripes: "2-8",
        Speed: 130,
        Price: 200,
        Image: image,
        Statusroad: "active",
        Startofsection: 322,
        Endofsection: 401,
      },{
        Roadid: 9,
        Name: "М-4 'Дон' 401км-464км",
        Trustmanagment: 1930,
        Length: 1542,
        Paidlength: 1042,
        Category: "1А, 1Б, 1В, II",
        Numberofstripes: "2-8",
        Speed: 130,
        Price: 200,
        Image: image,
        Statusroad: "active",
        Startofsection: 401,
        Endofsection: 464,
      },
      {
        Roadid: 10,
        Name: "М-4 'Дон' 492км-517км",
        Trustmanagment: 1930,
        Length: 1542,
        Paidlength: 1042,
        Category: "1А, 1Б, 1В, II",
        Numberofstripes: "2-8",
        Speed: 130,
        Price: 200,
        Image: image,
        Statusroad: "active",
        Startofsection: 492,
        Endofsection: 517,
      },
      {
        Roadid: 11,
        Name: "М-4 'Дон' 517км-544км",
        Trustmanagment: 1930,
        Length: 1542,
        Paidlength: 1042,
        Category: "1А, 1Б, 1В, II",
        Numberofstripes: "2-8",
        Speed: 130,
        Price: 200,
        Image: image,
        Statusroad: "active",
        Startofsection: 517,
        Endofsection: 544,
      },
      {
        Roadid: 12,
        Name: "М-4 'Дон' 544км-589км",
        Trustmanagment: 1930,
        Length: 1542,
        Paidlength: 1042,
        Category: "1А, 1Б, 1В, II",
        Numberofstripes: "2-8",
        Speed: 130,
        Price: 200,
        Image: image,
        Statusroad: "active",
        Startofsection: 544,
        Endofsection: 589,
      },
      {
        Roadid: 13,
        Name: "М-4 'Дон' 589км-633км",
        Trustmanagment: 1930,
        Length: 1542,
        Paidlength: 1042,
        Category: "1А, 1Б, 1В, II",
        Numberofstripes: "2-8",
        Speed: 130,
        Price: 200,
        Image: image,
        Statusroad: "active",
        Startofsection: 589,
        Endofsection: 633,
      },
      {
        Roadid: 14,
        Name: "М-4 'Дон' 633км-741км",
        Trustmanagment: 1930,
        Length: 1542,
        Paidlength: 1042,
        Category: "1А, 1Б, 1В, II",
        Numberofstripes: "2-8",
        Speed: 130,
        Price: 200,
        Image: image,
        Statusroad: "active",
        Startofsection: 633,
        Endofsection: 741,
      },
      {
        Roadid: 15,
        Name: "М-4 'Дон' 1024км-1091км",
        Trustmanagment: 1930,
        Length: 1542,
        Paidlength: 1042,
        Category: "1А, 1Б, 1В, II",
        Numberofstripes: "2-8",
        Speed: 130,
        Price: 200,
        Image: image,
        Statusroad: "active",
        Startofsection: 1024,
        Endofsection: 1091,
      },
      {
        Roadid: 16,
        Name: "М-4 'Дон' 1091км-1119км",
        Trustmanagment: 1930,
        Length: 1542,
        Paidlength: 1042,
        Category: "1А, 1Б, 1В, II",
        Numberofstripes: "2-8",
        Speed: 130,
        Price: 200,
        Image: image,
        Statusroad: "active",
        Startofsection: 1091,
        Endofsection: 1119,
      },
      {
        Roadid: 17,
        Name: "М-4 'Дон' 1119км-1195км",
        Trustmanagment: 1930,
        Length: 1542,
        Paidlength: 1042,
        Category: "1А, 1Б, 1В, II",
        Numberofstripes: "2-8",
        Speed: 130,
        Price: 200,
        Image: image,
        Statusroad: "active",
        Startofsection: 1119,
        Endofsection: 1195,
      },
      {
        Roadid: 18,
        Name: "М-4 'Дон' 1195км-1319км",
        Trustmanagment: 1930,
        Length: 1542,
        Paidlength: 1042,
        Category: "1А, 1Б, 1В, II",
        Numberofstripes: "2-8",
        Speed: 130,
        Price: 200,
        Image: image,
        Statusroad: "active",
        Startofsection: 1195,
        Endofsection: 1319,
      },
    ],
  };
  
  export default testData;